apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helm-guestbook.fullname" . }}-config
  labels:
    app: {{ template "helm-guestbook.name" . }}
    chart: {{ template "helm-guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ENTORNO: "Laboratorio-Hetzner"
  MENSAJE_BIENVENIDA: "¡Hola desde mi primer ConfigMap sincronizado por ArgoCD!"
